site_name: Full-Stack Machine Learning
repo_url: https://github.com/polyrand/fs-week
repo_name: polyrand/fs-week
base_url: https://polyrand.github.io/fs-week
site_url: https://polyrand.github.io/fs-week

theme:
   name: material
   language: en
   palette:
    primary: light blue
    accent: orange
plugins:
  - search
nav:
  - Introduction: 'index.md'
  - Documentation: 'documentation.md'
  - Running the apps: 'running.md'
  - Training: 'training.md'
  - Dependencies: 'dependency_management.md'
  - Models: 'models.md'
