site_name: Ricardo - Strive

theme:
   name: material
   language: en
plugins:
  - search
nav:
  - Introduction: 'index.md'
  - Documentation: 'documentation.md'
  - Running the apps: 'running.md'
  - Training: 'training.md'
  - Models: 'models.md'
