site_name: Ricardo - Strive

theme:
   name: material
   language: en
plugins:
  - search
nav:
  - Introduction: 'index.md'
  - Examples: 'examples.md'
  - Running: 'running.md'
  - Models: 'models.md'
