name: Tests
on: [push]
jobs:
  tests:
    name: random
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: some random step
        run: |
          python3 -c "print('hello')"
        # run: jupyter nbconvert --execute tests.ipynb --to notebook
