name: Tests
on: [push]
jobs:
  tests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip deps
        run: |
          pip install -U pip pip-tools
          pip-sync requirements/*.txt
      - name: runtests
        run: |
          python3 -m pytest -vv
      - name: Commit and push if it changed
        run: |
          timestamp=$(date -u)
          echo $timestamp > latest_push.timestamp
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
        # run: jupyter nbconvert --execute tests.ipynb --to notebook
